python experiments/step_program/run_step_program_v3_1_no_router_matrix_chain.py \
  --synthetic \
  --device cuda \
  --amp fp16 \
  --classes yes,no,up,down,left,right,on,off,stop,go \
  --train-limit 512 \
  --val-limit 256 \
  --batch-size 64 \
  --eval-batch-size 128 \
  --workers 0 \
  --dim 64 \
  --evidence-cells 48 \
  --layers 3 \
  --blocks 3 \
  --steps 2 \
  --substeps 1 \
  --rank 16 \
  --groups 4 \
  --max-gain 0.50 \
  --epochs 2 \
  --max-train-batches 4 \
  --max-val-batches 2 \
  --log-every 1 \
  --grad-analytics-every 1 \
  --out-dir ./runs/step_program_v3_1_no_router_chain_smoke
